DISABLE_IPv6=false
ENABLE_STATIC_IP=false
ENABLE_AUTOHOTSPOT=true
AUTOHOTSPOT_SSID=phoniebox
AUTOHOTSPOT_PASSWORD=YeahImNotCommitingThisToGit
AUTOHOTSPOT_COUNTRYCODE=DE
AUTOHOTSPOT_IP=10.0.0.2
DISABLE_BLUETOOTH=false
DISABLE_ONBOARD_AUDIO=false # Already done via target.sdmconfig
SETUP_MPD=true
ENABLE_MPD_OVERWRITE_INSTALL=true
ENABLE_RFID_READER=false # Installation is hardcoded instead
ENABLE_SAMBA=false
ENABLE_WEBAPP=true
ENABLE_WEBAPP_PROD_DOWNLOAD=false # Force build to avoid getting into git-mess
ENABLE_KIOSK_MODE=false